### ISSUE TITLE
blender crashes whenever i try to import goddards head

### ISSUE THREAD

**Issue by beaswag** [SIsilicon/Goddard-ImportExport-Project#1]
i just downloaded the addon and whenever i try to import Goddard blender just closes without any warning
this happens every time i try to do it

im using blender 2.83.2 and the source path i have set is `E:\apps\sm64PCBuilder\sm64ex-nightly\`
i have `c memory management` disabled every time and i have the Default Cube™ selected as well

**Comment by SIsilicon** [comment]
The add-on was built in blender 2.9.
See if it works in that version.

**Comment by beaswag** [comment]
still doesnt work
sorry for late response

**Comment by beaswag** [comment]
nvm it works
